a.out : normal_dist.cpp graph.py
	g++ normal_dist.cpp
	./a.out 1 5000 3.5 0.4 2.7 4.6 50 > datos1.txt
	./a.out 2 5000 3.5 0.4 2.7 4.6 50 > datos2.txt
	./a.out 5 5000 3.5 0.4 2.7 4.6 50 > datos5.txt
	python graph.py
